routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/role', 'RoleController');
Route::resource('/user', 'UserController');

Route::group(['middleware' => ['acl']], function () {
    Route::resource('/department', 'DepartmentController');
});

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use RealRashid\SweetAlert\Facades\Alert;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $roles = Role::paginate(15);

        return view('role.index', compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $permissionModules = Permission::where('parent_permission', 0)->get()->groupBy('module');
        $rolePermissions = collect([]);

        return view('role.form', compact('permissionModules', 'rolePermissions'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:roles',
            'permissions' => 'required',
        ]);

        $role = new Role();
        $role->name = $request->name;
        $role->save();

        $childPermissions = Permission::whereIn('parent_permission', $request->permissions)->pluck('id')->toArray();
        $permissions = array_merge($request->permissions, $childPermissions);

        $role->givePermissionTo($permissions);

        Alert::success('Role added');

        return redirect(route('role.create'));
    }

    /**
     * Display the specified resource.
     *
     * @param \Spatie\Permission\Models\Role $role
     * @return \Illuminate\Http\Response
     */
    public function show(Permission $permission)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param \Spatie\Permission\Models\Role $role
     * @return \Illuminate\Http\Response
     */
    public function edit(Role $role)
    {
        $permissionModules = Permission::where('parent_permission', 0)->get()->groupBy('module');
        $rolePermissions = $role->getAllPermissions()->pluck('id');

        return view('role.form', compact('role', 'permissionModules', 'rolePermissions'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param \Spatie\Permission\Models\Role $role
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Role $role)
    {
        $this->validate($request, [
            'name' => 'required|unique:roles,name,' . $role->id . ',id'
        ]);

        $role->name = $request->name;
        $role->save();

        $childPermissions = Permission::whereIn('parent_permission', $request->permissions)->pluck('id')->toArray();
        $permissions = array_merge($request->permissions, $childPermissions);

        $role->syncPermissions($permissions);

        Alert::success('Role updated');

        return redirect(route('role.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param \Spatie\Permission\Models\Role $role
     * @return \Illuminate\Http\Response
     */
    public function destroy(Role $role)
    {
        $role->permissions()->detach();
        $role->delete();

        Alert::success('Role deleted');

        return redirect(route('role.index'));
    }
}

resources/views/role/form.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        Create New Role
                        <a href="{{route('role.index')}}" class="btn btn-sm btn-primary" style="float: right">Back
                            to List</a>
                    </div>

                    <div class="card-body">
                        @include('layouts.errors')

                        @if(!isset($role))
                            {!! Form::open(['route' => 'role.store']) !!}
                        @else
                            {!! Form::model($role, ['route' => ['role.update', $role->id], 'method' => 'put'])  !!}
                        @endif

                        <div class="form-group">
                            {!! Form::label('name', 'Name') !!}
                            {!! Form::text('name', NULL, ['placeholder' => 'Enter role name', 'class' => 'form-control']) !!}
                        </div>

                        <div class="form-group">
                            {!! Form::label('', 'Permissions') !!}

                            <table class="table table-bordered table-condensed">
                                <thead>
                                <tr>
                                    <th>SL</th>
                                    <th>Module</th>
                                    <th>Permission</th>
                                </tr>
                                </thead>
                                <tbody>
                                @php $i = 1 @endphp
                                @foreach($permissionModules as $k => $permissions)
                                <tr>
                                    <td>{{ $i++ }}</td>
                                    <td>{{ $k }}</td>
                                    <td>
                                        @foreach($permissions as $permission)
                                            <label>{!! Form::checkbox('permissions[]', $permission->id, $rolePermissions->search($permission->id) !== false); !!} {{ $permission->permission }}</label>
                                        @endforeach
                                    </td>
                                </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>

                        {!! Form::submit(isset($role) ? 'Update' : 'Save', ['class' => 'btn btn-success btn-sm']) !!}
                        {!! Form::button('Reset', ['type' => 'reset', 'class' => 'btn btn-danger btn-sm']) !!}

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/role/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        Role
                        <a href="{{route('role.create')}}" class="btn btn-sm btn-primary" style="float: right">Create
                            New Role</a>
                    </div>

                    <div class="card-body">
                        @if (session('status'))
                            <div class="alert alert-success" role="alert">
                                {{ session('status') }}
                            </div>
                        @endif

                        <table class="table table-bordered table-condensed">
                            <thead>
                            <tr>
                                <th width="50" class="text-center">SL</th>
                                <th class="text-center">Name</th>
                                <th width="135" class="text-center">Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($roles as $k => $role)
                                <tr>
                                    <td class="text-center">{{ $roles->firstItem() + $k }}</td>
                                    <td>{{ $role->name }}</td>
                                    <td class="text-center">
                                        <a href="{{ route('role.edit', $role->id) }}"
                                           class="btn btn-sm btn-primary">Edit</a>

                                        {!! Form::open(['route' => ['role.destroy', $role->id], 'method' => 'delete', 'class' => 'delete-form']) !!}
                                        {!! Form::submit('Delete', ['class' => 'btn btn-sm btn-danger']); !!}
                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>

                        {{ $roles->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection